export const USERS_MODULE_NAME = 'users'

export const USERS_STATE = {
  USERS: 'USERS',
  CURRENT_USER: 'CURRENT_USER'
}

export const USERS_ACTIONS = {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USER: 'FETCH_USER',
  REMOVE_USER: 'REMOVE_USER',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  CREATE_USER: 'CREATE_USER'
}

export const USERS_MUTATIONS = {
  SET_USERS: 'SET_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER'
}
