export const MENUS_MODULE_NAME = 'menus'

export const MENUS_STATE = {
  MENUS: 'MENUS',
  CURRENT_MENU: 'CURRENT_MENU',
}

export const MENUS_ACTIONS = {
  FETCH_MENUS: 'FETCH_MENUS',
  FETCH_MENU: 'FETCH_MENU',
  UPDATE_MENU_LINKS: 'UPDATE_MENU_LINKS',
  UPDATE_CURRENT_MENU: 'UPDATE_MENU'
}

export const MENUS_MUTATIONS = {
  SET_MENUS: 'SET_MENUS',
  SET_CURRENT_MENU: 'SET_CURRENT_MENU',
  SET_UPDATED_LINKS: 'SET_UPDATED_LINKS'
}

export const MENUS_GETTERS = {
  CURRENT_MENU_LINKS: 'CURRENT_MENU_LINKS'
}
