export const POSTS_MODULE_NAME = 'posts'

export const POSTS_STATE = {
  POSTS: 'POSTS',
  CURRENT_POST: 'CURRENT_POST'
}

export const POSTS_ACTIONS = {
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  UPDATE_CURRENT_POST: 'UPDATE_POST',
  CREATE_POST: 'CREATE_POST',
  REMOVE_POST: 'REMOVE_POST'
}

export const POSTS_MUTATIONS = {
  SET_POSTS: 'SET_POSTS',
  SET_CURRENT_POST: 'SET_CURRENT_POST'
}
