export const CATEGORIES_MODULE_NAME = 'categories'

export const CATEGORIES_STATE = {
  CATEGORIES: 'CATEGORIES',
  CATEGORIES_LOADED: 'CATEGORIES_LOADED',
  CURRENT_CATEGORY: 'CURRENT_CATEGORY'
}

export const CATEGORIES_ACTIONS = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_CATEGORY: 'FETCH_CATEGORY',
  UPDATE_CURRENT_CATEGORY: 'UPDATE_CATEGORY'
}

export const CATEGORIES_MUTATIONS = {
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY'
}
