export const CONFIGURATIONS_MODULE_NAME = 'configurations'

export const CONFIGURATIONS_STATE = {
  CONFIGURATIONS: 'CONFIGURATIONS',
  CONFIGURATIONS_LOADED: 'CONFIGURATIONS_LOADED',
  CURRENT_CONFIGURATION: 'CURRENT_CONFIGURATION'
}

export const CONFIGURATIONS_ACTIONS = {
  FETCH_CONFIGURATIONS: 'FETCH_CONFIGURATIONS',
  FETCH_CONFIGURATION: 'FETCH_CONFIGURATION',
  UPDATE_CURRENT_CONFIGURATION: 'UPDATE_CONFIGURATION'
}

export const CONFIGURATIONS_MUTATIONS = {
  SET_CONFIGURATIONS: 'SET_CONFIGURATIONS',
  SET_CURRENT_CONFIGURATION: 'SET_CURRENT_CONFIGURATION'
}
