export const CONFIGURATIONS_MODULE_NAME = 'configurations'

export const CONFIGURATIONS_STATE = {
  CONFIGURATIONS: 'CONFIGURATIONS',
  CONFIGURATIONS_LOADED: 'CONFIGURATIONS_LOADED',
  CONFIGURATIONS_LOADING: 'CONFIGURATIONS_LOADING',
  CURRENT_CONFIGURATION: 'CURRENT_CONFIGURATION',
  PROMISES: 'PROMISES'
}

export const CONFIGURATIONS_ACTIONS = {
  FETCH_CONFIGURATIONS: 'FETCH_CONFIGURATIONS',
  FETCH_CONFIGURATION: 'FETCH_CONFIGURATION',
  UPDATE_CURRENT_CONFIGURATION: 'UPDATE_CONFIGURATION'
}

export const CONFIGURATIONS_MUTATIONS = {
  SET_CONFIGURATIONS: 'SET_CONFIGURATIONS',
  SET_CONFIGURATION_LOADED: 'SET_CONFIGURATION_LOADED',
  SET_CONFIGURATION_LOADING: 'SET_CONFIGURATION_LOADING',
  SET_CURRENT_CONFIGURATION: 'SET_CURRENT_CONFIGURATION',
  SET_PROMISES: 'SET_PROMISES'
}
